In [21]:
import pandas as pd

#手動dict建立DataFrame
pd.DataFrame({"徐xx":[67, 92, 82],
              "張xx":[98, 78, 69],
              "王xx":[76, 65, 83]},index=['國文','英文','數學'])

    徐xx  張xx  王xx
國文   67   98   76
英文   92   78   65
數學   82   69   83

In [22]:
#手動2維list建立DataFrame
pd.DataFrame([[67, 98, 76],
              [92, 78, 65],
              [82, 69, 83]],index=['國文','英文','數學'],columns=['徐xx','張xx','王xx'])

    徐xx  張xx  王xx
國文   67   98   76
英文   92   78   65
數學   82   69   83

In [23]:
#手動2維list建立DataFrame
pd.DataFrame([{"徐xx":67,'張xx':98,'王xx':76},
              {"徐xx":67,'張xx':98,'王xx':76},
              {"徐xx":67,'張xx':98,'王xx':76}
              ],index=['國文','英文','數學'])

    徐xx  張xx  王xx
國文   67   98   76
英文   67   98   76
數學   67   98   76

In [24]:
import numpy as np
import pandas as pd

scores = np.random.randint(60,100,size=(50,5))
students = pd.DataFrame(scores,index=range(1,51),columns=["國文","英文","數學","地理","歷史"])
students

    國文  英文  數學  地理  歷史
1   93  77  99  95  61
2   71  75  77  76  99
3   60  91  86  75  90
4   88  91  97  96  84
5   71  98  60  64  76
6   61  75  64  77  70
7   84  86  98  75  98
8   81  99  63  95  91
9   90  72  77  71  84
10  86  95  97  80  95
11  65  91  88  91  96
12  70  88  91  75  94
13  64  82  91  88  78
14  96  71  63  68  77
15  81  63  93  84  63
16  77  91  96  85  75
17  83  74  95  99  95
18  76  64  95  85  81
19  63  79  68  75  68
20  81  83  60  77  81
21  87  64  79  66  91
22  88  74  93  66  72
23  93  78  86  60  62
24  62  77  97  68  96
25  65  82  67  64  67
26  99  66  70  86  83
27  60  97  62  60  98
28  91  96  83  84  93
29  74  73  92  96  85
30  99  82  75  80  90
31  80  60  79  65  91
32  63  82  79  67  92
33  91  85  98  79  65
34  83  72  86  74  97
35  91  60  84  99  91
36  95  69  80  97  82
37  91  73  60  72  67
38  95  60  77  78  71
39  60  86  89  88  93
40  65  60  71  66  77
41  93  64  89  60  97
42  94  92  60  80  60
43  78  82  62  60  91
44  97  89  89  98  68
45  64  96  84  80  64
46  78  65  71  92  70
47  81  60  62  71  70
48  70  69  91  74  78
49  81  72  60  62  61
50  65  96  76  83  83

In [25]:
#使用subscript->['字串'],選欄
#使用subscript->[1:5],選列
students['國文']
students[['國文','英文']]

    國文  英文
1   93  77
2   71  75
3   60  91
4   88  91
5   71  98
6   61  75
7   84  86
8   81  99
9   90  72
10  86  95
11  65  91
12  70  88
13  64  82
14  96  71
15  81  63
16  77  91
17  83  74
18  76  64
19  63  79
20  81  83
21  87  64
22  88  74
23  93  78
24  62  77
25  65  82
26  99  66
27  60  97
28  91  96
29  74  73
30  99  82
31  80  60
32  63  82
33  91  85
34  83  72
35  91  60
36  95  69
37  91  73
38  95  60
39  60  86
40  65  60
41  93  64
42  94  92
43  78  82
44  97  89
45  64  96
46  78  65
47  81  60
48  70  69
49  81  72
50  65  96

In [26]:
students[0:1]

   國文  英文  數學  地理  歷史
1  93  77  99  95  61

In [27]:
#students.loc[]
#studnets.iloc[]

students.loc[50] , students.iloc[49]

(國文    65
 英文    96
 數學    76
 地理    83
 歷史    83
 Name: 50, dtype: int64,
 國文    65
 英文    96
 數學    76
 地理    83
 歷史    83
 Name: 50, dtype: int64)

In [28]:
#前5位學生
students.loc[1:5], students.iloc[0:5]

(   國文  英文  數學  地理  歷史
 1  93  77  99  95  61
 2  71  75  77  76  99
 3  60  91  86  75  90
 4  88  91  97  96  84
 5  71  98  60  64  76,
    國文  英文  數學  地理  歷史
 1  93  77  99  95  61
 2  71  75  77  76  99
 3  60  91  86  75  90
 4  88  91  97  96  84
 5  71  98  60  64  76)

In [29]:
students.loc[1]

國文    93
英文    77
數學    99
地理    95
歷史    61
Name: 1, dtype: int64

In [30]:
#不建議的寫法
one = students.loc[1]
one.sum()

425

In [31]:
students.loc[1].sum()

425

In [32]:
students.sum(axis=1)

1     425
2     398
3     402
4     456
5     369
6     347
7     441
8     429
9     394
10    453
11    431
12    418
13    403
14    375
15    384
16    424
17    446
18    401
19    353
20    382
21    387
22    393
23    379
24    400
25    345
26    404
27    377
28    447
29    420
30    426
31    375
32    383
33    418
34    412
35    425
36    423
37    363
38    381
39    416
40    339
41    403
42    386
43    373
44    441
45    388
46    376
47    344
48    382
49    336
50    403
dtype: int64

In [33]:
students['總分'] = students.sum(axis=1)
students

    國文  英文  數學  地理  歷史   總分
1   93  77  99  95  61  425
2   71  75  77  76  99  398
3   60  91  86  75  90  402
4   88  91  97  96  84  456
5   71  98  60  64  76  369
6   61  75  64  77  70  347
7   84  86  98  75  98  441
8   81  99  63  95  91  429
9   90  72  77  71  84  394
10  86  95  97  80  95  453
11  65  91  88  91  96  431
12  70  88  91  75  94  418
13  64  82  91  88  78  403
14  96  71  63  68  77  375
15  81  63  93  84  63  384
16  77  91  96  85  75  424
17  83  74  95  99  95  446
18  76  64  95  85  81  401
19  63  79  68  75  68  353
20  81  83  60  77  81  382
21  87  64  79  66  91  387
22  88  74  93  66  72  393
23  93  78  86  60  62  379
24  62  77  97  68  96  400
25  65  82  67  64  67  345
26  99  66  70  86  83  404
27  60  97  62  60  98  377
28  91  96  83  84  93  447
29  74  73  92  96  85  420
30  99  82  75  80  90  426
31  80  60  79  65  91  375
32  63  82  79  67  92  383
33  91  85  98  79  65  418
34  83  72  86  74  97  412
35  91  60  84  99  91  425
36  95  69  80  97  82  423
37  91  73  60  72  67  363
38  95  60  77  78  71  381
39  60  86  89  88  93  416
40  65  60  71  66  77  339
41  93  64  89  60  97  403
42  94  92  60  80  60  386
43  78  82  62  60  91  373
44  97  89  89  98  68  441
45  64  96  84  80  64  388
46  78  65  71  92  70  376
47  81  60  62  71  70  344
48  70  69  91  74  78  382
49  81  72  60  62  61  336
50  65  96  76  83  83  403

In [34]:
students[['國文','英文','數學', '地理','歷史']]

    國文  英文  數學  地理  歷史
1   93  77  99  95  61
2   71  75  77  76  99
3   60  91  86  75  90
4   88  91  97  96  84
5   71  98  60  64  76
6   61  75  64  77  70
7   84  86  98  75  98
8   81  99  63  95  91
9   90  72  77  71  84
10  86  95  97  80  95
11  65  91  88  91  96
12  70  88  91  75  94
13  64  82  91  88  78
14  96  71  63  68  77
15  81  63  93  84  63
16  77  91  96  85  75
17  83  74  95  99  95
18  76  64  95  85  81
19  63  79  68  75  68
20  81  83  60  77  81
21  87  64  79  66  91
22  88  74  93  66  72
23  93  78  86  60  62
24  62  77  97  68  96
25  65  82  67  64  67
26  99  66  70  86  83
27  60  97  62  60  98
28  91  96  83  84  93
29  74  73  92  96  85
30  99  82  75  80  90
31  80  60  79  65  91
32  63  82  79  67  92
33  91  85  98  79  65
34  83  72  86  74  97
35  91  60  84  99  91
36  95  69  80  97  82
37  91  73  60  72  67
38  95  60  77  78  71
39  60  86  89  88  93
40  65  60  71  66  77
41  93  64  89  60  97
42  94  92  60  80  60
43  78  82  62  60  91
44  97  89  89  98  68
45  64  96  84  80  64
46  78  65  71  92  70
47  81  60  62  71  70
48  70  69  91  74  78
49  81  72  60  62  61
50  65  96  76  83  83

In [35]:
students.loc[1:50]

    國文  英文  數學  地理  歷史   總分
1   93  77  99  95  61  425
2   71  75  77  76  99  398
3   60  91  86  75  90  402
4   88  91  97  96  84  456
5   71  98  60  64  76  369
6   61  75  64  77  70  347
7   84  86  98  75  98  441
8   81  99  63  95  91  429
9   90  72  77  71  84  394
10  86  95  97  80  95  453
11  65  91  88  91  96  431
12  70  88  91  75  94  418
13  64  82  91  88  78  403
14  96  71  63  68  77  375
15  81  63  93  84  63  384
16  77  91  96  85  75  424
17  83  74  95  99  95  446
18  76  64  95  85  81  401
19  63  79  68  75  68  353
20  81  83  60  77  81  382
21  87  64  79  66  91  387
22  88  74  93  66  72  393
23  93  78  86  60  62  379
24  62  77  97  68  96  400
25  65  82  67  64  67  345
26  99  66  70  86  83  404
27  60  97  62  60  98  377
28  91  96  83  84  93  447
29  74  73  92  96  85  420
30  99  82  75  80  90  426
31  80  60  79  65  91  375
32  63  82  79  67  92  383
33  91  85  98  79  65  418
34  83  72  86  74  97  412
35  91  60  84  99  91  425
36  95  69  80  97  82  423
37  91  73  60  72  67  363
38  95  60  77  78  71  381
39  60  86  89  88  93  416
40  65  60  71  66  77  339
41  93  64  89  60  97  403
42  94  92  60  80  60  386
43  78  82  62  60  91  373
44  97  89  89  98  68  441
45  64  96  84  80  64  388
46  78  65  71  92  70  376
47  81  60  62  71  70  344
48  70  69  91  74  78  382
49  81  72  60  62  61  336
50  65  96  76  83  83  403

In [36]:
students['平均'] = students.iloc[:,:5].mean(axis=1)
students

    國文  英文  數學  地理  歷史   總分    平均
1   93  77  99  95  61  425  85.0
2   71  75  77  76  99  398  79.6
3   60  91  86  75  90  402  80.4
4   88  91  97  96  84  456  91.2
5   71  98  60  64  76  369  73.8
6   61  75  64  77  70  347  69.4
7   84  86  98  75  98  441  88.2
8   81  99  63  95  91  429  85.8
9   90  72  77  71  84  394  78.8
10  86  95  97  80  95  453  90.6
11  65  91  88  91  96  431  86.2
12  70  88  91  75  94  418  83.6
13  64  82  91  88  78  403  80.6
14  96  71  63  68  77  375  75.0
15  81  63  93  84  63  384  76.8
16  77  91  96  85  75  424  84.8
17  83  74  95  99  95  446  89.2
18  76  64  95  85  81  401  80.2
19  63  79  68  75  68  353  70.6
20  81  83  60  77  81  382  76.4
21  87  64  79  66  91  387  77.4
22  88  74  93  66  72  393  78.6
23  93  78  86  60  62  379  75.8
24  62  77  97  68  96  400  80.0
25  65  82  67  64  67  345  69.0
26  99  66  70  86  83  404  80.8
27  60  97  62  60  98  377  75.4
28  91  96  83  84  93  447  89.4
29  74  73  92  96  85  420  84.0
30  99  82  75  80  90  426  85.2
31  80  60  79  65  91  375  75.0
32  63  82  79  67  92  383  76.6
33  91  85  98  79  65  418  83.6
34  83  72  86  74  97  412  82.4
35  91  60  84  99  91  425  85.0
36  95  69  80  97  82  423  84.6
37  91  73  60  72  67  363  72.6
38  95  60  77  78  71  381  76.2
39  60  86  89  88  93  416  83.2
40  65  60  71  66  77  339  67.8
41  93  64  89  60  97  403  80.6
42  94  92  60  80  60  386  77.2
43  78  82  62  60  91  373  74.6
44  97  89  89  98  68  441  88.2
45  64  96  84  80  64  388  77.6
46  78  65  71  92  70  376  75.2
47  81  60  62  71  70  344  68.8
48  70  69  91  74  78  382  76.4
49  81  72  60  62  61  336  67.2
50  65  96  76  83  83  403  80.6

In [37]:
students.to_csv('學生第一學期分數.csv')

In [38]:
weather = pd.read_csv('最新的氣象預測.csv')
weather

,城市,起始時間,結束時間,最高溫度,最低溫度,感覺
0,臺北市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
1,新北市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
2,桃園市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,31,29,悶熱
3,臺中市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,31,29,悶熱
4,臺南市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
5,高雄市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
6,基隆市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,28,悶熱
7,新竹縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,32,30,悶熱
8,新竹市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,32,30,悶熱
9,苗栗縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,32,30,悶熱
10,彰化縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,31,29,悶熱
11,南投縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,28,舒適至悶熱
12,雲林縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,28,悶熱
13,嘉義縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
14,嘉義市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,27,舒適至悶熱
15,屏東縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,28,27,舒適至悶熱
16,宜蘭縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,28,悶熱
17,花蓮縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,28,悶熱
18,臺東縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,28,舒適至悶熱
19,澎湖縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,31,28,悶熱
20,金門縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,33,29,悶熱
21,連江縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,27,悶熱